# Generated by Django 2.0.1 on 2018-01-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=60)),
                ('item_from', models.CharField(max_length=20)),
                ('item_to', models.CharField(max_length=20)),
                ('item_arrive_time', models.DateTimeField()),
                ('item_description', models.CharField(blank=True, max_length=150)),
                ('item_price', models.FloatField(max_length=10)),
                ('item_price_currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
