# Generated by Django 2.0.1 on 2018-01-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
