# Generated by Django 2.0.1 on 2018-01-21 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='userbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='useremail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
